export enum ErrorCode {
  DB_CONNECT_FAIL = 'DB_CONNECT_FAIL',
  INTERNAL_SERVER = 'INTERNAL_SERVER',
  TOKEN_VERIFY_FAILED = "TOKEN_VERIFY_FAILED",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  PASSWORD_INVALID = "PASSWORD_INVALID"
}